"""Open a GitHub PR carrying an agent-proposed SQL fix.

LLM-authored SQL is never auto-merged: PRs are opened as drafts and labelled
needs-review (the agent sets requires_human_review on the action). Branch names
are idempotency-keyed so a re-fired action reuses the existing PR rather than
spamming duplicates.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any

from github import Github, GithubException

logger = logging.getLogger(__name__)


class GitHubPRCreator:
    def __init__(self, token: str, repo: str) -> None:
        self._gh = Github(token)
        self.repo = self._gh.get_repo(repo)

    def _existing_pr_url(self, branch_name: str) -> str | None:
        """Return the URL of an open PR for this branch, if one exists."""
        owner = self.repo.owner.login
        for pr in self.repo.get_pulls(state="open", head=f"{owner}:{branch_name}"):
            return str(pr.html_url)
        return None

    def create_fix_pr(
        self,
        event: Any,
        fix_sql: str,
        model_file_path: str,
        impact_summary: str,
        risk_level: str = "medium",
        branch_name: str | None = None,
        draft: bool = True,
    ) -> str:
        atype = getattr(event.anomaly_type, "value", event.anomaly_type)
        if branch_name is None:
            ts = datetime.utcnow().strftime("%Y%m%d%H%M%S")
            branch_name = f"fix/impact-{atype}-{ts}"

        # Idempotency: reuse an existing open PR for this branch.
        existing = self._existing_pr_url(branch_name)
        if existing:
            logger.info("PR already open for %s: %s", branch_name, existing)
            return existing

        default_branch = self.repo.default_branch
        base_sha = self.repo.get_branch(default_branch).commit.sha
        try:
            self.repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)
        except GithubException as e:
            if e.status != 422:  # 422 = ref already exists
                raise

        # Update the model file on the branch.
        contents = self.repo.get_contents(model_file_path, ref=branch_name)
        self.repo.update_file(
            path=model_file_path,
            message=f"fix({atype}): defensive update to {model_file_path}",
            content=fix_sql,
            sha=contents.sha,  # type: ignore[union-attr]
            branch=branch_name,
        )

        body = self._pr_body(event, impact_summary, risk_level)
        pr = self.repo.create_pull(
            title=f"[auto] Fix {atype} on {event.source_node_id}",
            body=body,
            head=branch_name,
            base=default_branch,
            draft=draft,
        )
        try:
            pr.add_to_labels("auto-generated", risk_level, "needs-review")
        except GithubException as e:
            logger.warning("could not add labels: %s", e)
        return str(pr.html_url)

    @staticmethod
    def _pr_body(event: Any, impact_summary: str, risk_level: str) -> str:
        atype = getattr(event.anomaly_type, "value", event.anomaly_type)
        return (
            f"## Autonomous Impact Analyst — proposed fix\n\n"
            f"**Anomaly:** `{atype}` on `{event.source_node_id}`"
            f"{f' (column `{event.source_column}`)' if event.source_column else ''}\n"
            f"**Risk level:** {risk_level}\n\n"
            f"### Impact summary\n{impact_summary}\n\n"
            f"---\n"
            f"⚠️ This SQL was generated by an LLM and validated only for parse "
            f"correctness. **Human review required before merge.**\n"
        )
