"""
scripts/verify_raw_tables.py

Connect to Databricks and verify the 7 raw tables seeded by
`scripts/seed_databricks.py`:

- Print SELECT COUNT(*) for each
- Emit DESCRIBE TABLE output to docs/raw_table_schemas.md

`docs/raw_table_schemas.md` is the contract for Phase 2 staging models;
those models reference these exact column names.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any

from databricks import sql
from dotenv import load_dotenv

load_dotenv()

DATABRICKS_HOST = os.environ["DATABRICKS_HOST"]
DATABRICKS_HTTP_PATH = os.environ["DATABRICKS_HTTP_PATH"]
DATABRICKS_TOKEN = os.environ["DATABRICKS_TOKEN"]
CATALOG = os.environ.get("DATABRICKS_CATALOG", "workspace")
RAW_SCHEMA = os.environ.get("DATABRICKS_SCHEMA_RAW", "raw")

TABLES = [
    "coingecko_coins_markets",
    "coingecko_coins_detail",
    "coingecko_exchanges",
    "defi_llama_protocols",
    "defi_llama_yields_pools",
    "etherscan_eth_transactions",
    "etherscan_token_transfers",
]

DOC_PATH = Path(__file__).resolve().parent.parent / "docs" / "raw_table_schemas.md"


def count_rows(cur: Any, fq: str) -> int:
    cur.execute(f"SELECT COUNT(*) FROM {fq}")
    return int(cur.fetchone()[0])


def describe(cur: Any, fq: str) -> list[tuple[str, str, str | None]]:
    """Return [(col_name, data_type, comment)]. Stops at the first divider row."""
    cur.execute(f"DESCRIBE TABLE {fq}")
    out: list[tuple[str, str, str | None]] = []
    for row in cur.fetchall():
        name = (row[0] or "").strip()
        # Databricks DESCRIBE returns a divider then partition info; stop there.
        if not name or name.startswith("#"):
            break
        dtype = (row[1] or "").strip()
        comment = (row[2] if len(row) > 2 else None)
        out.append((name, dtype, comment))
    return out


def main() -> int:
    print(f"Connecting to Databricks ({DATABRICKS_HOST})...")
    conn = sql.connect(
        server_hostname=DATABRICKS_HOST,
        http_path=DATABRICKS_HTTP_PATH,
        access_token=DATABRICKS_TOKEN,
    )
    failures: list[str] = []
    md_parts: list[str] = [
        "# Raw Table Schemas",
        "",
        (
            f"Auto-generated by `scripts/verify_raw_tables.py`. "
            f"Catalog: `{CATALOG}`, schema: `{RAW_SCHEMA}`."
        ),
        "",
        (
            "Phase 2 staging models depend on these exact column names. "
            "All columns are STRING; type casting happens in the staging layer."
        ),
        "",
    ]
    try:
        with conn.cursor() as cur:
            for t in TABLES:
                fq = f"{CATALOG}.{RAW_SCHEMA}.{t}"
                try:
                    n = count_rows(cur, fq)
                except Exception as e:
                    print(f"  {t}: ERROR ({e})")
                    failures.append(t)
                    continue
                marker = "OK" if n > 0 else "EMPTY"
                print(f"  {t}: {n} rows [{marker}]")
                if n == 0:
                    failures.append(t)

                cols = describe(cur, fq)
                md_parts.append(f"## `{RAW_SCHEMA}.{t}` ({n} rows)")
                md_parts.append("")
                md_parts.append("| Column | Type | Comment |")
                md_parts.append("|---|---|---|")
                for name, dtype, comment in cols:
                    md_parts.append(f"| `{name}` | {dtype} | {comment or ''} |")
                md_parts.append("")
    finally:
        conn.close()

    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text("\n".join(md_parts))
    print(f"\nWrote {DOC_PATH.relative_to(Path.cwd())}")

    if failures:
        print(f"\nFAILED: {len(failures)} table(s) empty or unreadable: {failures}")
        return 1
    print(f"\nAll {len(TABLES)} raw tables populated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
